### ISSUE TITLE
Rename to coreos-vultr?

### ISSUE THREAD

**Issue by michielbdejong** [pierreozoux/bootstrap-vultr#1]
Looking at the code, it seems that this is a bootstrap for starting a generic CoreOS VPS on Vultr.com hosting, right? So maybe the name coreos-vultr is better?

Also, is that your public ssh key in there? It would be better if that's a command line parameter or something, or make it take use `~/.ssh/id_rsa.pub` be default, so other people can also use this? ( without giving you access to all their VPSs :)

**Comment by pierreozoux** [comment]
Yes, totally agree for the rename! I like the idea of having access to all VPS ;) Yes, obviously, it would be better if it is done programmatically. I'll take care of that.

**Comment by michielbdejong** [comment]
@pierreozoux If we rename it to coreos-vultr, then it's no longer related to IndieHosters I guess, so would it make sense to also change ownership of this repo to you, then?

**Comment by pierreozoux** [comment]
Yep, sorry, I moved it under my name, I'll deal with it later.
